//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/ProjectResources/DevToolPanel/DevActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DevActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DevActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DevActions"",
    ""maps"": [
        {
            ""name"": ""Devel"",
            ""id"": ""25f65344-6c2e-4638-beb6-623dda32fa85"",
            ""actions"": [
                {
                    ""name"": ""DevPanel"",
                    ""type"": ""Button"",
                    ""id"": ""1f5b402e-dff2-4d3b-8bb8-1417e3a232ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""84000d00-d174-4068-9893-628600fdb3cf"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevPanel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Devel
        m_Devel = asset.FindActionMap("Devel", throwIfNotFound: true);
        m_Devel_DevPanel = m_Devel.FindAction("DevPanel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Devel
    private readonly InputActionMap m_Devel;
    private List<IDevelActions> m_DevelActionsCallbackInterfaces = new List<IDevelActions>();
    private readonly InputAction m_Devel_DevPanel;
    public struct DevelActions
    {
        private @DevActions m_Wrapper;
        public DevelActions(@DevActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @DevPanel => m_Wrapper.m_Devel_DevPanel;
        public InputActionMap Get() { return m_Wrapper.m_Devel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DevelActions set) { return set.Get(); }
        public void AddCallbacks(IDevelActions instance)
        {
            if (instance == null || m_Wrapper.m_DevelActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DevelActionsCallbackInterfaces.Add(instance);
            @DevPanel.started += instance.OnDevPanel;
            @DevPanel.performed += instance.OnDevPanel;
            @DevPanel.canceled += instance.OnDevPanel;
        }

        private void UnregisterCallbacks(IDevelActions instance)
        {
            @DevPanel.started -= instance.OnDevPanel;
            @DevPanel.performed -= instance.OnDevPanel;
            @DevPanel.canceled -= instance.OnDevPanel;
        }

        public void RemoveCallbacks(IDevelActions instance)
        {
            if (m_Wrapper.m_DevelActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDevelActions instance)
        {
            foreach (var item in m_Wrapper.m_DevelActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DevelActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DevelActions @Devel => new DevelActions(this);
    public interface IDevelActions
    {
        void OnDevPanel(InputAction.CallbackContext context);
    }
}
